services:

  synchtank:
    container_name: synchtank
    image: synchtank
    restart: always
    build:
      context: .
      args:
        PROJECT_NAME: synchtank
        TARGET: backend:latest
    ports:
      - "30220:80"
    links:
      - synchtank-postgres
    networks:
      network:
        ipv4_address: 30.30.30.220
    depends_on:
      - synchtank-postgres

  synchtank-postgres:
    container_name: synchtank-postgres
    image: synchtank-postgres
    restart: always
    build:
      context: docker/db
      args:
        REMOTE_IMAGE: postgres:17.5
    shm_size: 1g
    environment:
      POSTGRES_USER: "synchtank"
      POSTGRES_PASSWORD: "synchtank"
      POSTGRES_DB: "synchtank"
    volumes:
      - postgres-synchtank-data:/var/lib/postgresql/data
    ports:
      - "30321:5432"
    networks:
      network:
        ipv4_address: 30.30.30.221

volumes:
  postgres-synchtank-data:

networks:
  network:
    external:
      name: network-shared
